version: '3.7'
services:

  backend:
    build: ./todo-be
    container_name: todo-backend
    ports:
    - "9090:9090"
    volumes:
    - .:/todo-be-volume
  frontend:
    build: ./todo-fe
    container_name: todo-frontend
    ports:
    - "8080:8080"
    volumes:
    - .:/todo-fe-volume
    links:
    - backend