
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  email VARCHAR(250) NOT NULL,
  passwordHash VARCHAR(500) NOT NULL
);


CREATE TABLE IF NOT EXISTS todos (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  text VARCHAR(250) NOT NULL,
  user_id INT NOT NULL
);